//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorOP
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DOPEntities : DbContext
    {
        public DOPEntities()
            : base("name=DOPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PatientDetail> PatientDetail { get; set; }
        public virtual DbSet<PatientRefraction> PatientRefraction { get; set; }
        public virtual DbSet<Patientvisit> Patientvisit { get; set; }
        public virtual DbSet<Medicin_tbl> Medicin_tbl { get; set; }
        public virtual DbSet<PatientSummary> PatientSummary { get; set; }
        public virtual DbSet<Payment_tbl> Payment_tbl { get; set; }
    }
}
