//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorOP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicin_tbl
    {
        public int Id { get; set; }
        public string Med_Id { get; set; }
        public string Med_Name { get; set; }
        public string Med_type { get; set; }
        public string Med_Qty { get; set; }
        public string Med_Price { get; set; }
        public string Creat_Date { get; set; }
    }
}
