//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorOP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient_Visit_Detail
    {
        public string patient_id { get; set; }
        public string patient_name { get; set; }
        public string patient_mobile { get; set; }
        public string patient_city { get; set; }
        public string patient_gender { get; set; }
        public string patient_eye { get; set; }
        public string patient_visitid { get; set; }
        public string patient_Complaint { get; set; }
        public string Visitdate { get; set; }
        public string nextvisit { get; set; }
        public int Id { get; set; }
    }
}
