//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorOP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient_Med_Detail
    {
        public int Id { get; set; }
        public string med_id { get; set; }
        public string med_name { get; set; }
        public string med_price { get; set; }
        public string med_qty { get; set; }
        public string med_Type { get; set; }
    }
}
