//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorOP
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientDetail
    {
        public int Id { get; set; }
        public string patient_id { get; set; }
        public string patient_name { get; set; }
        public string patient_mobile { get; set; }
        public string patient_occupation { get; set; }
        public string patient_address { get; set; }
        public string patient_city { get; set; }
        public string patient_district { get; set; }
        public string patient_pincode { get; set; }
        public string Visitdate { get; set; }
    }
}
