//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorOP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient_Ref_Detail
    {
        public int Id { get; set; }
        public string AXIS_OD { get; set; }
        public string AXIS_OS { get; set; }
        public string CYL_OD { get; set; }
        public string CYL_OS { get; set; }
        public string SPH_OD { get; set; }
        public string SPH_OS { get; set; }
        public string VISION_OD { get; set; }
        public string VISION_OS { get; set; }
        public string patient_visitid { get; set; }
    }
}
